---
title: "How can you use the MsBackendRawFileReader package as developer?"
author:
- name: Christian Panse
  affiliation: Functional Genomics Center Zurich
  email: cp@fgcz.ethz.ch
- name: Tobias Kockmann
  affiliation: Functional Genomics Center Zurich
  email: tobias.Kockmann@fgcz.ethz.ch
package: MsBackendRawFileReader
output:
  BiocStyle::html_document
abstract: |
  xxx xxx xxx `r Githubpkg("rformassspectrometry/Spectra")`  [@Huber2015, @Trachsel2018]
vignette: |
  %\VignetteIndexEntry{For Developer}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
bibliography:
  - MsBackendRawFileReader.bib
---


# First steps

## Manually stating the `CLRServer.exe`

```{bash eval=FALSE}
/Library/Frameworks/Mono.framework/Commands/mono64 \
  --llvm /Library/Frameworks/R.framework/Versions/3.6/Resources/library/rDotNet/server/bin/Debug/CLRServer.exe \
  -url svc://localhost:56789/ \
  -dll /Library/Frameworks/R.framework/Versions/3.6/Resources/library/MsBackendRawFileReader/exec/MsBackendRawFileReader.dll
```


## Attach the package

```{r debugging, eval=TRUE, message=FALSE, warning=FALSE}
library(MsBackendRawFileReader)

(rawfile <- file.path(path.package(package = 'MsBackendRawFileReader'),
                                'extdata', 'sample.raw'))
```



# Constructor

call the constructor for a given rawfile
```{r debuggingCallConstructor}
x <- .cnew ("Rawfile", rawfile)
```

# Call the C# object methods

call methods of the C# class
```{r debuggingHaveFun}
x$GetMsLevel(1)

vapply(1:10, FUN=function(z){x$GetMsLevel(z)}, FUN.VALUE=as.integer(1))

head(x$GetSpectrumMasses(1))

```

# Extra Header Information

```{r debuggingExtraHeaderInformation}
x$GetTrailerExtraHeaderInformationLabel()
```

```{r kableExtraHeader, echo=FALSE, comment='GetTrailerExtraHeaderInformation'}
#dfExtraHeader[1:3,]
```

# On using filters

see also [@RawfileReader2015, page 28]

```{r filters}
x$GetAutoFilters()

x$IsValidFilter("most likely not a valid filter string")
x$IsValidFilter("ms2 776.9297@hcd28.00")
```

```{r eval=FALSE}
x$GetMsLevels()

x$GetTotalIonCounts()
x$GetRtime()

```


# Spectra

```{r noise, fig.retina=3}
mZ <- x$GetSpectrumMasses(2)

noise <- x$GetSpectrumNoises(2)

intensity <- x$GetSpectrumIntensities(2)

plot(intensity ~ mZ, type='h', ylim=c(0, max(intensity)))

lines(mZ, noise, col='red')
```

# XIC 

```{r}
rawfile <- "/Users/cp/Downloads/20191021_033_autoQC4L.raw"
x <- .cnew ("Rawfile", rawfile)

isoMz <- c(428.2738, 424.2667, 420.7581, 417.7512, 414.7443)

S <- x$GetXIC(isoMz, 10)

vec2XIC <- function(x){
    df <- data.frame(times=x[seq(1, length(x), by=2)], intensities=x[seq(2, length(x), by=2)])
    df[df$intensities > 0,]
}

SS <- split(S, gl(length(isoMz),length(S)/length(isoMz)))

SSS <- lapply(SS, vec2XIC)

op <- par(mfrow=c(5,1))
rv <- lapply(SSS, plot, type='l')
```


# Session Info

```{r sessionInfo}
sessionInfo()
```

#References




