---
title: "Howto use the `MsBackendRawFileReader`?"
author:
- name: Christian Panse
  affiliation: Functional Genomics Center Zurich
  email: cp@fgcz.ethz.ch
- name: Tobias Kockmann
  affiliation: Functional Genomics Center Zurich
  email: tobias.Kockmann@fgcz.ethz.ch
package: MsBackendRawFileReader
output:
  BiocStyle::html_document
abstract: |
  `r BiocStyle::Githubpkg("fgcz/MsBackendRawFileReader")` implements an
  MsBackend for the `r BiocStyle::Biocpkg("Spectra")` package using
  Thermo Fisher Scientific's NewRawFileReader .Net libraries.
  The package is generalizing the functionallity provided by the
  `r BiocStyle::Biocpkg("rawrr")`.
vignette: |
  %\VignetteIndexEntry{Howto use the package?}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
bibliography:
  - MsBackendRawFileReader.bib
---

# Usage

```{r require}
stopifnot(require(Spectra), require(MsBackendRawFileReader), require(BiocParallel))
```


```{r tartareEH4547, warning=FALSE, message=FALSE, eval=TRUE}
# fetch via ExperimentHub
library(ExperimentHub)
eh <- ExperimentHub::ExperimentHub()
```

```{r tartare}
query(eh, c('tartare'))
```

```{r EH3220, message=FALSE, warning=FALSE, echo=FALSE}
EH3220 <- normalizePath(eh[["EH3220"]])
(rawfileEH3220 <- paste0(EH3220, ".raw"))
if (!file.exists(rawfileEH3220)){
  file.link(EH3220, rawfileEH3220)
}

EH3222 <- normalizePath(eh[["EH3222"]])
(rawfileEH3222 <- paste0(EH3222, ".raw"))
if (!file.exists(rawfileEH3222)){
  file.link(EH3222, rawfileEH3222)
}

EH4547  <- normalizePath(eh[["EH4547"]])
(rawfileEH4547  <- paste0(EH4547 , ".raw"))
if (!file.exists(rawfileEH4547 )){
  file.link(EH4547 , rawfileEH4547 )
}
```

```{r EH3219}
EH3219 <- normalizePath(eh[["EH3219"]])
EH3221 <- normalizePath(eh[["EH3221"]])
EH4547 <- normalizePath(eh[["EH4547"]])
```

call the constructor

```{r librarySnippet, message=FALSE}
beRaw <- Spectra::backendInitialize(MsBackendRawFileReader::MsBackendRawFileReader(),
                                    files = c(rawfileEH3220, rawfileEH3222, rawfileEH4547))
```

```{r show}
beRaw
```


# Have Fun


```{r}
(beRaw |> 
   filterScan("FTMS + c NSI Full ms2 487.2567@hcd27.00 [100.0000-1015.0000]") )[437] |> 
  plotSpectra()

(yIonSeries <- protViz::fragmentIon("LGGNEQVTR")[[1]]$y[1:8])
names(yIonSeries) <- paste0("y", seq(1, length(yIonSeries)))
abline(v = yIonSeries, col='#DDDDDD88', lwd=5)
axis(3, yIonSeries, names(yIonSeries))
```

## Extent Class

write a method for filtering spectra if fragment ions exists.

```{r}
setGeneric("filterIons", function(object, ...) standardGeneric("filterIons"))

setMethod("filterIons", "MsBackend",
  function(object, mZ=numeric(), tol=numeric(), ...) {
    
    keep <- lapply(peaksData(object),
                           FUN=function(x){
                             NN <- protViz::findNN(mZ, x[,1])
                             hit <- (error <- yIonSeries - x[NN,1]) < tol
                             if (sum(hit) == length(mZ))
                               TRUE
                             else
                               FALSE
                           })
    
    object[unlist(keep)]
  })
```

apply it the the example

```{r}
beRaw |> 
  filterScan("FTMS + c NSI Full ms2 487.2567@hcd27.00 [100.0000-1015.0000]") |>
  filterIons(yIonSeries, tol=0.0005) |> 
  plotSpectra()
```

# Session information

```{r si}
sessionInfo()
```

# References