---
title: "On how to a read Thermo Fisher raw file into R"
author:
- name: Christian Panse
  affiliation: Functional Genomics Center Zurich
  email: cp@fgcz.ethz.ch
- name: Tobias Kockmann
  affiliation: Functional Genomics Center Zurich
  email: tobias.Kockmann@fgcz.ethz.ch
package: MsBackendRawFileReader
output:
  BiocStyle::html_document
abstract: |
  xxx xxx xxx `r Biocpkg("Spectra")`  [@Huber2015, @Trachsel2018]
vignette: |
  %\VignetteIndexEntry{Howto read Thermo-Fisher raw files?}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
bibliography:
  - MsBackendRawFileReader.bib
---

 
# Simple usage

```{r librarySnippet, message=FALSE}
library(MsBackendRawFileReader)

(fls <- file.path(path.package(package = 'MsBackendRawFileReader'),
                                'extdata', 'sample.raw'))

```

```{r HelloWorldSnippet, message=FALSE}
be <- backendInitialize(MsBackendRawFileReader(), files = fls)

(sps_thermofinnigan <- Spectra(be))
```

# Session Info

```{r}
sessionInfo()
```

#References


