---
title: "tartare"
author:
- name: Christian Panse
  affiliation: Functional Genomics Center Zurich
  email: cp@fgcz.ethz.ch
- name: Tobias Kockmann
  affiliation: Functional Genomics Center Zurich
  email: tobias.Kockmann@fgcz.ethz.ch
package: MsBackendRawFileReader
output:
  BiocStyle::html_document
abstract: |
  This file helps to compare spectra variables depended on using different
  Orbitrap instruments and file formats using 
  `r Githubpkg("rformassspectrometry/Spectra")` and 
  `r Githubpkg("cpanse/MsBackendRawfileReader")` [@Trachsel2018].
vignette: |
  %\VignetteIndexEntry{Compare spectraVariable ~ file format * instrument}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
bibliography:
  - MsBackendRawFileReader.bib
---


# First steps

## Attach the packages

```{r attach, eval=TRUE, message=FALSE, warning=FALSE}
library(MsBackendRawFileReader)
library(tartare)
```

## Define input

```{r filenames}
fl <- system.file("extdata", "metadata.csv", package="tartare")   
metadata <- read.csv(fl, stringsAsFactors=FALSE)

files <- file.path(path.expand("~"), metadata$RDataPath)
```


## Load data using the `MsBackend`s

```{r MsBackend}

be <- lapply(files, function(f){
     if (grepl("mzXML$", f)){
         backendInitialize(MsBackendMzR(), files = f)
     }
     else
         backendInitialize(MsBackendRawFileReader(), files = f, extra=TRUE)
})
   

(S <- lapply(be, Spectra))
```


```{r shape, echo=FALSE}
SV <- lapply(S, spectraVariables)
desc <- paste(metadata$Title)

SS <- do.call('rbind', 
           lapply(1:4, function(i){
               df <- data.frame(spectraVariables=SV[i]);
           df$file <- desc[i]; 
           df}))

names(SS) <- c('spectraVariables', 'file')
```

# Compare `spectraVariable ~ file format * instrument`


## Graph using `lattice::dotplot`

```{r dotplot, fig.retina=3, fig.width=20, fig.height=4}
library(lattice)
dotplot(~ spectraVariables | file ,
        data = SS,
        horizontal = FALSE,
        scales = list(x = list(rot = 45)),
        layout = c(1,4))
```


## Display using `kableExtra`

```{r determineOverlab, echo=FALSE, message=FALSE, warning=FALSE}
df <- data.frame(names=names(table(SS$spectraVariables)))
df$HFX.raw <- FALSE
df$Fusion.raw <- FALSE
df$HFX.mzXML <- FALSE
df$Fusion.mzXML <- FALSE

df$HFX.mzXML <- df$names %in% spectraVariables(S[[1]])
df$HFX.raw <- df$names %in% spectraVariables(S[[2]])

df$Fusion.mzXML <- df$names %in% spectraVariables(S[[3]])
df$Fusion.raw <- df$names %in% spectraVariables(S[[4]])

```

```{r kableOverlab, echo=FALSE, message=FALSE, warning=FALSE}
library(knitr)
library(tidyverse)
library(kableExtra)
df %>% 
    mutate(
        names=names,
        HFX.raw=cell_spec(HFX.raw, "html", color = ifelse(HFX.raw, 'cornflowerblue', 'white')),
        Fusion.raw=cell_spec(Fusion.raw, "html", color = ifelse(Fusion.raw, 'cornflowerblue', 'white')),
        HFX.mzXML=cell_spec(HFX.mzXML, "html", color = ifelse(HFX.mzXML, 'cornflowerblue', 'white')),
        Fusion.mzXML=cell_spec(Fusion.mzXML, "html", color = ifelse(Fusion.mzXML, 'cornflowerblue', 'white'))
        ) %>%
    kable(format = "html", escape = F)%>%
    kable_styling("hover", full_width = F) %>%
    column_spec(5, width = "3cm") 
```

# Session info

Here is the compiled output of `sessionInfo()`:

```{r sessionInfo, echo=FALSE}
sessionInfo()
```


# References